# Generated by Django 5.1.3 on 2024-12-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notification_is_read_notification_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='group_profiles/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='group_covers/')),
                ('category', models.CharField(choices=[('study', 'Study Group'), ('sports', 'Sports Group'), ('work', 'Work Group'), ('gaming', 'Gaming Group'), ('hobby', 'Hobby Group'), ('social', 'Social Group')], max_length=20)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('hidden', 'Hidden')], max_length=20)),
            ],
        ),
    ]
