site_name: Django Project Documentation
nav:
  - Home: index.md
  - Backend:
      - Overview: backend/overview.md
      - Models: backend/models.md
      - Workflows: backend/workflows.md
  - Frontend:
      - Components: frontend/components.md
      - Styles: frontend/styles.md
theme:
  name: material
